/**
 * @fileoverview Full quiz question bank for CivicMind AI.
 * 40+ questions across all election stages.
 */

export const QUESTION_BANK = [
  // ── ANNOUNCEMENT ──────────────────────────────────────────
  {
    id: 'q_ann_01', stage: 'announcement', difficulty: 'easy',
    question: 'Who is responsible for announcing election dates in India?',
    options: ['Prime Minister', 'President of India', 'Election Commission of India', 'Supreme Court'],
    correctIndex: 2,
    explanation: 'The Election Commission of India (ECI) is an autonomous constitutional authority responsible for administering election processes in India, including announcing election schedules.',
    xpReward: 30,
  },
  {
    id: 'q_ann_02', stage: 'announcement', difficulty: 'easy',
    question: 'What is the Model Code of Conduct (MCC)?',
    options: ['A law passed by Parliament', 'A set of guidelines for parties and candidates during elections', 'A voter registration manual', 'A document for EVM maintenance'],
    correctIndex: 1,
    explanation: 'The MCC is a set of guidelines issued by the ECI for political parties and candidates to ensure free and fair elections. It comes into effect from the date of announcement of the election schedule.',
    xpReward: 30,
  },
  {
    id: 'q_ann_03', stage: 'announcement', difficulty: 'medium',
    question: 'When does the Model Code of Conduct come into effect?',
    options: ['On voting day', 'A week before voting', 'Immediately after election schedule announcement', 'On counting day'],
    correctIndex: 2,
    explanation: 'The MCC comes into force immediately after the announcement of the election schedule by the ECI and remains in force until the completion of the election process.',
    xpReward: 40,
  },
  {
    id: 'q_ann_04', stage: 'announcement', difficulty: 'medium',
    question: 'How many phases did the 2024 Indian General Election have?',
    options: ['3', '5', '7', '9'],
    correctIndex: 2,
    explanation: 'The 2024 Indian General Election was conducted in 7 phases from April 19 to June 1, 2024.',
    xpReward: 40,
  },
  {
    id: 'q_ann_05', stage: 'announcement', difficulty: 'hard',
    question: 'Under which article of the Constitution does the ECI derive its power to supervise elections?',
    options: ['Article 324', 'Article 356', 'Article 370', 'Article 21'],
    correctIndex: 0,
    explanation: 'Article 324 of the Constitution vests the superintendence, direction, and control of elections in the Election Commission of India.',
    xpReward: 50,
  },

  // ── REGISTRATION ──────────────────────────────────────────
  {
    id: 'q_reg_01', stage: 'registration', difficulty: 'easy',
    question: 'What is the minimum age to register as a voter in India?',
    options: ['16 years', '18 years', '21 years', '25 years'],
    correctIndex: 1,
    explanation: 'A citizen of India who is 18 years of age or above on the qualifying date (January 1st of the year) is eligible to register as a voter.',
    xpReward: 30,
  },
  {
    id: 'q_reg_02', stage: 'registration', difficulty: 'easy',
    question: 'What document is issued to a registered voter?',
    options: ['Aadhaar Card', 'PAN Card', 'Voter ID Card (EPIC)', 'Passport'],
    correctIndex: 2,
    explanation: 'EPIC (Electors Photo Identity Card) is the Voter ID Card issued by the ECI to registered voters. It serves as proof of identity at polling booths.',
    xpReward: 30,
  },
  {
    id: 'q_reg_03', stage: 'registration', difficulty: 'medium',
    question: 'Which form is used to register as a new voter in India?',
    options: ['Form 6', 'Form 7', 'Form 8', 'Form 9'],
    correctIndex: 0,
    explanation: 'Form 6 is used for inclusion of name in electoral rolls for the first time. Form 7 is for deletion, and Form 8 is for correction of entries.',
    xpReward: 40,
  },
  {
    id: 'q_reg_04', stage: 'registration', difficulty: 'hard',
    question: 'What is the Systematic Voters Education and Electoral Participation (SVEEP) program?',
    options: ['A voter registration fraud detection system', "ECI's flagship program for voter education and participation", 'A scheme to replace EVMs', 'A government job program for election officers'],
    correctIndex: 1,
    explanation: 'SVEEP is the Election Commission of India\'s flagship program for voter education, spread of voter awareness, and promotion of voter literacy in India.',
    xpReward: 50,
  },
  {
    id: 'q_reg_05', stage: 'registration', difficulty: 'medium',
    question: 'Can an NRI (Non-Resident Indian) vote in Indian elections?',
    options: ['No, NRIs cannot vote', 'Yes, but only via postal ballot', 'Yes, but they must be physically present at their polling booth', 'Yes, they can vote online'],
    correctIndex: 2,
    explanation: 'NRIs holding an Indian passport are eligible to vote, but they must be physically present at their designated polling booth in India on the day of voting. Online voting is not currently available.',
    xpReward: 40,
  },

  // ── NOMINATION ────────────────────────────────────────────
  {
    id: 'q_nom_01', stage: 'nomination', difficulty: 'easy',
    question: 'What is the minimum age to contest for a Lok Sabha seat?',
    options: ['18 years', '21 years', '25 years', '30 years'],
    correctIndex: 2,
    explanation: 'According to Article 84 of the Constitution, a person must be at least 25 years of age to be eligible for membership of Lok Sabha.',
    xpReward: 30,
  },
  {
    id: 'q_nom_02', stage: 'nomination', difficulty: 'medium',
    question: 'What security deposit does a general candidate pay for a Lok Sabha election?',
    options: ['₹5,000', '₹10,000', '₹25,000', '₹50,000'],
    correctIndex: 2,
    explanation: 'General candidates must deposit ₹25,000 as security deposit for Lok Sabha elections. SC/ST candidates pay ₹12,500. The deposit is forfeited if the candidate fails to get more than 1/6th of valid votes.',
    xpReward: 40,
  },
  {
    id: 'q_nom_03', stage: 'nomination', difficulty: 'medium',
    question: 'What must candidates declare in their affidavit at time of nomination?',
    options: ['Their party membership', 'Their assets, liabilities, and criminal records', 'Their education certificates only', 'Their future policy plans'],
    correctIndex: 1,
    explanation: 'Candidates must file an affidavit declaring their criminal antecedents, assets and liabilities of themselves and their spouse and dependents, and educational qualifications.',
    xpReward: 40,
  },
  {
    id: 'q_nom_04', stage: 'nomination', difficulty: 'hard',
    question: 'A candidate\'s nomination can be rejected if:',
    options: ['They belong to a regional party', 'Their nomination papers are improperly signed or they are disqualified', 'They have not won a previous election', 'They do not have a college degree'],
    correctIndex: 1,
    explanation: 'Nominations can be rejected if the nomination paper is not in the prescribed format, the candidate is disqualified under any law, or required securities have not been deposited.',
    xpReward: 50,
  },
  {
    id: 'q_nom_05', stage: 'nomination', difficulty: 'hard',
    question: 'How many proposers are required for a candidate set up by a recognized National or State Party?',
    options: ['1 elector', '5 electors', '10 electors', '20 electors'],
    correctIndex: 0,
    explanation: 'A candidate set up by a recognized National or State Party requires only 1 elector of the constituency as a proposer. Independent candidates or those from unrecognized parties require 10 proposers.',
    xpReward: 50,
  },

  // ── CAMPAIGN ──────────────────────────────────────────────
  {
    id: 'q_cam_01', stage: 'campaign', difficulty: 'easy',
    question: 'When does the campaign period end before election day?',
    options: ['12 hours before', '24 hours before', '48 hours before', '72 hours before'],
    correctIndex: 2,
    explanation: 'The campaign period ends 48 hours before the scheduled closing time of polling. This is called the "campaign silence" period to allow voters to make an uninfluenced decision.',
    xpReward: 30,
  },
  {
    id: 'q_cam_02', stage: 'campaign', difficulty: 'medium',
    question: 'What is the maximum election expenditure limit for a Lok Sabha candidate?',
    options: ['₹25 Lakh', '₹50 Lakh', '₹70 Lakh', '₹95 Lakh'],
    correctIndex: 3,
    explanation: 'The Election Commission revised the expenditure limit for Lok Sabha candidates to ₹95 lakh in larger states. This limit ensures a level playing field.',
    xpReward: 40,
  },
  {
    id: 'q_cam_03', stage: 'campaign', difficulty: 'medium',
    question: 'Which of the following is a "corrupt practice" under election law?',
    options: ['Holding a rally', 'Distributing money or gifts to voters', 'Publishing election manifesto', 'Door-to-door canvassing'],
    correctIndex: 1,
    explanation: 'Bribery — the distribution of money, gifts, or any other gratification to voters — is a corrupt practice under the Representation of the People Act, 1951, and can lead to election being declared void.',
    xpReward: 40,
  },
  {
    id: 'q_cam_04', stage: 'campaign', difficulty: 'hard',
    question: 'What is "paid news" in the context of Indian elections?',
    options: ['News paid for by the government', 'Media coverage presented as news but paid for by political parties/candidates', 'Subscription-based news services', 'News from foreign media'],
    correctIndex: 1,
    explanation: '"Paid news" refers to any news or analysis appearing in print or electronic media which apparently is paid for, but is presented as editorial content to mislead voters. ECI monitors this.',
    xpReward: 50,
  },
  {
    id: 'q_cam_05', stage: 'campaign', difficulty: 'medium',
    question: 'Is it legal to appeal to voters in the name of religion or caste?',
    options: ['Yes, if it is a regional party', 'Yes, during private meetings only', 'No, it is a corrupt practice', 'No, unless authorized by the ECI'],
    correctIndex: 2,
    explanation: 'Appealing to voters on the grounds of religion, race, caste, community, or language is strictly prohibited under the Representation of the People Act and is considered a corrupt practice.',
    xpReward: 40,
  },

  // ── VOTING ────────────────────────────────────────────────
  {
    id: 'q_vot_01', stage: 'voting', difficulty: 'easy',
    question: 'What does EVM stand for?',
    options: ['Electronic Voting Machine', 'Election Verification Module', 'Electronic Vote Meter', 'Election Value Monitor'],
    correctIndex: 0,
    explanation: 'EVM stands for Electronic Voting Machine. India introduced EVMs to replace paper ballots and make elections more efficient, accurate, and tamper-proof.',
    xpReward: 30,
  },
  {
    id: 'q_vot_02', stage: 'voting', difficulty: 'easy',
    question: 'What is VVPAT?',
    options: ['Voter Verified Paper Audit Trail', 'Voting Verification Printed Address Ticket', 'Virtual Voter Print and Track', 'Verified Voting Paper Approval Trail'],
    correctIndex: 0,
    explanation: 'VVPAT (Voter Verified Paper Audit Trail) is a device attached to the EVM which provides visual verification to the voter that their vote has been recorded correctly as a paper slip.',
    xpReward: 30,
  },
  {
    id: 'q_vot_03', stage: 'voting', difficulty: 'medium',
    question: 'What is the minimum distance rule for campaigning near a polling booth?',
    options: ['50 meters', '100 meters', '200 meters', '500 meters'],
    correctIndex: 1,
    explanation: 'No person can do any electioneering, including displaying symbols, within a distance of 100 meters of a polling station on the day of the poll.',
    xpReward: 40,
  },
  {
    id: 'q_vot_04', stage: 'voting', difficulty: 'medium',
    question: 'What is "booth capturing"?',
    options: ['Taking a photo inside a polling booth', 'Taking control of a polling booth to cast fraudulent votes', 'Counting votes at a booth', 'Assigning voters to booths'],
    correctIndex: 1,
    explanation: 'Booth capturing refers to the illegal act of taking over a polling station by force or intimidation to cast fraudulent votes. It is a serious election offense.',
    xpReward: 40,
  },
  {
    id: 'q_vot_05', stage: 'voting', difficulty: 'hard',
    question: 'Which Article of the Indian Constitution guarantees the right to vote?',
    options: ['Article 19', 'Article 21', 'Article 326', 'Article 324'],
    correctIndex: 2,
    explanation: 'Article 326 of the Indian Constitution provides for elections to the Lok Sabha and state legislatures on the basis of adult suffrage — every citizen who is 18 years or older has the right to vote.',
    xpReward: 50,
  },

  // ── COUNTING ──────────────────────────────────────────────
  {
    id: 'q_cnt_01', stage: 'counting', difficulty: 'easy',
    question: 'Who supervises the counting of votes?',
    options: ['State Government Officials', 'Returning Officer appointed by ECI', 'Supreme Court Judges', 'Army Officers'],
    correctIndex: 1,
    explanation: 'The Returning Officer (RO), appointed by the Election Commission of India, is responsible for the overall conduct of counting of votes in their constituency.',
    xpReward: 30,
  },
  {
    id: 'q_cnt_02', stage: 'counting', difficulty: 'medium',
    question: 'What is a "postal ballot"?',
    options: ['A ballot delivered via post to absent voters', 'A ballot cast by the postal department', 'A digital vote cast online', 'A vote counted last'],
    correctIndex: 0,
    explanation: 'Postal ballots allow eligible voters (service personnel, election duty officials, overseas citizens in some cases) to cast their vote by post when they cannot be physically present at the polling booth.',
    xpReward: 40,
  },
  {
    id: 'q_cnt_03', stage: 'counting', difficulty: 'hard',
    question: 'What happens if a candidate secures exactly 1/6th of total valid votes?',
    options: ['They win the election', 'They get their security deposit back', 'Their security deposit is forfeited', 'A re-election is held'],
    correctIndex: 2,
    explanation: 'A candidate who fails to secure more than 1/6th (i.e., more than 16.67%) of the total valid votes polled in the constituency loses their security deposit to the government.',
    xpReward: 50,
  },
  {
    id: 'q_cnt_04', stage: 'counting', difficulty: 'medium',
    question: 'In what order are the votes generally counted?',
    options: ['EVM votes first, then Postal Ballots', 'Postal Ballots first, then EVM votes', 'Simultaneously', 'Depending on the RO\'s preference'],
    correctIndex: 1,
    explanation: 'Under ECI guidelines, the counting of Postal Ballots is taken up first. After a gap of 30 minutes, the counting of votes recorded in EVMs begins.',
    xpReward: 40,
  },
  {
    id: 'q_cnt_05', stage: 'counting', difficulty: 'hard',
    question: 'What is the purpose of counting VVPAT slips?',
    options: ['To replace EVM counting completely', 'To randomly verify EVM counts for accuracy', 'To distribute to candidates as proof', 'To count postal ballots electronically'],
    correctIndex: 1,
    explanation: 'VVPAT slips from 5 randomly selected polling stations per assembly constituency are counted to cross-verify and ensure the accuracy and integrity of the EVM results.',
    xpReward: 50,
  },

  // ── RESULTS ───────────────────────────────────────────────
  {
    id: 'q_res_01', stage: 'results', difficulty: 'easy',
    question: 'How many seats are required for a simple majority in Lok Sabha?',
    options: ['200', '243', '272', '300'],
    correctIndex: 2,
    explanation: 'The Lok Sabha has 543 elected members. A simple majority requires more than half, i.e., at least 272 seats, to form a government.',
    xpReward: 30,
  },
  {
    id: 'q_res_02', stage: 'results', difficulty: 'medium',
    question: 'What is a "hung parliament"?',
    options: ['A parliament dissolved before its term', 'A parliament where no single party wins a majority', 'A parliament that is suspended', 'A parliament with 100% voter turnout'],
    correctIndex: 1,
    explanation: 'A hung parliament occurs when no single political party or pre-existing coalition wins an outright majority of seats, forcing parties to negotiate a coalition or minority government.',
    xpReward: 40,
  },
  {
    id: 'q_res_03', stage: 'results', difficulty: 'medium',
    question: 'What is a "by-election" (उप-चुनाव)?',
    options: ['Election held alongside the main election', 'Election held to fill a vacant seat mid-term', 'Election held in border areas', 'Election with a smaller voter base'],
    correctIndex: 1,
    explanation: 'A by-election (upchunav) is held to fill a vacancy that arises in the middle of a term, due to the death, resignation, or disqualification of the elected representative.',
    xpReward: 40,
  },
  {
    id: 'q_res_04', stage: 'results', difficulty: 'hard',
    question: 'Under the anti-defection law, when can an elected member be disqualified?',
    options: ['If they criticize their party leader', 'If they voluntarily give up party membership or vote against party whip', 'If they are absent for more than 30 days', 'If they fail to attend Parliament regularly'],
    correctIndex: 1,
    explanation: 'The Tenth Schedule (anti-defection law) disqualifies a member if they voluntarily give up party membership or vote/abstain contrary to the party\'s direction (whip) without prior permission.',
    xpReward: 50,
  },
  {
    id: 'q_res_05', stage: 'results', difficulty: 'hard',
    question: 'Who administers the oath of office to the newly elected Prime Minister?',
    options: ['Chief Justice of India', 'Chief Election Commissioner', 'President of India', 'Speaker of the Lok Sabha'],
    correctIndex: 2,
    explanation: 'The President of India administers the oath of office and secrecy to the Prime Minister and other members of the Council of Ministers.',
    xpReward: 50,
  },

  // ── GENERAL CIVIC KNOWLEDGE ───────────────────────────────
  {
    id: 'q_gen_01', stage: 'general', difficulty: 'easy',
    question: 'What does NOTA stand for in Indian elections?',
    options: ['None Of The Above', 'No Other Trusted Alternative', 'Not On The Agenda', 'National Option for Total Abstinence'],
    correctIndex: 0,
    explanation: 'NOTA (None Of The Above) is an option on the EVM ballot that allows voters to officially register their disapproval of all candidates without casting a vote for any of them. It was introduced in 2013.',
    xpReward: 30,
  },
  {
    id: 'q_gen_02', stage: 'general', difficulty: 'easy',
    question: 'India has what type of electoral system for Lok Sabha elections?',
    options: ['Proportional Representation', 'First-Past-The-Post (FPTP)', 'Ranked Choice Voting', 'Two-Round System'],
    correctIndex: 1,
    explanation: 'India uses the First-Past-The-Post (FPTP) system, where the candidate with the most votes in a constituency wins, regardless of whether they have an absolute majority.',
    xpReward: 30,
  },
  {
    id: 'q_gen_03', stage: 'general', difficulty: 'medium',
    question: 'How often are Lok Sabha elections held in India?',
    options: ['Every 3 years', 'Every 5 years', 'Every 6 years', 'Every 7 years'],
    correctIndex: 1,
    explanation: 'The Lok Sabha has a term of 5 years from the date of its first sitting, after which elections must be held. The President can dissolve it earlier on the advice of the PM.',
    xpReward: 40,
  },
  {
    id: 'q_gen_04', stage: 'general', difficulty: 'medium',
    question: 'What is the Election Commission of India (ECI)?',
    options: ['A ministry under the central government', 'An autonomous constitutional body', 'A department of the Supreme Court', 'A statutory body under Parliament'],
    correctIndex: 1,
    explanation: 'The ECI is an autonomous constitutional body, established under Article 324 of the Constitution, responsible for administering election processes in India.',
    xpReward: 40,
  },
  {
    id: 'q_gen_05', stage: 'general', difficulty: 'hard',
    question: 'Which constitutional article establishes the Election Commission of India?',
    options: ['Article 315', 'Article 320', 'Article 324', 'Article 329'],
    correctIndex: 2,
    explanation: 'Article 324 of the Indian Constitution vests the superintendence, direction and control of the preparation of electoral rolls and the conduct of all elections to Parliament and State Legislatures in the Election Commission of India.',
    xpReward: 50,
  },
  {
    id: 'q_gen_06', stage: 'general', difficulty: 'hard',
    question: 'The Representation of the People Act was passed in which year?',
    options: ['1947', '1949', '1951', '1956'],
    correctIndex: 2,
    explanation: 'The Representation of the People Act, 1951 is the primary legislation in India that governs elections to the Parliament and state legislatures, and the conduct of elections.',
    xpReward: 50,
  },
];

export const QUIZ_QUESTIONS = QUESTION_BANK;

export const CHAT_CHIPS = [
  'How do I register to vote?',
  'What is the Model Code of Conduct?',
  'How does an EVM work?',
  'What is VVPAT?',
  'What is NOTA?',
  'Who can contest elections?',
];
