import React, { useState } from 'react';
import AdaptiveQuiz from './AdaptiveQuiz.jsx';
import KnowledgeQuiz from './KnowledgeQuiz.jsx';
import useJourney from '../hooks/useJourney';
import { Sparkles, Globe, ChevronRight } from 'lucide-react';

export default function QuizView() {
  const [activeMode, setActiveMode] = useState(null); // 'ai' or 'global'
  const [selectedStageId, setSelectedStageId] = useState(null);
  const { allStages, currentStage } = useJourney();

  if (activeMode === 'global') {
    return (
      <div style={{ height: '100%', overflowY: 'auto', padding: '20px', width: '100%' }}>
        <KnowledgeQuiz onReset={() => setActiveMode(null)} />
      </div>
    );
  }

  if (activeMode === 'ai' && selectedStageId) {
    return (
      <div style={{ height: '100%', overflowY: 'auto', padding: '20px', width: '100%' }}>
        <AdaptiveQuiz stageId={selectedStageId} onReset={() => { setActiveMode(null); setSelectedStageId(null); }} />
      </div>
    );
  }

  return (
    <div style={{ height: '100%', overflowY: 'auto', padding: '20px' }}>
      <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
        <div style={{ textAlign: 'center', marginBottom: '48px' }}>
          <h1 className="text-hero" style={{ marginBottom: '16px' }}>Training Grounds</h1>
          <p className="text-body" style={{ maxWidth: '600px', margin: '0 auto' }}>
            Test your civic knowledge and earn XP. Choose between tailored AI missions for specific stages or the global knowledge challenge.
          </p>
        </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '24px', marginBottom: '48px' }}>
        {/* AI Missions Card */}
        <div className="card premium-card-glass" style={{ padding: '32px', display: 'flex', flexDirection: 'column' }}>
          <div style={{ width: '48px', height: '48px', background: 'var(--blue-subtle)', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '24px' }}>
            <Sparkles size={24} className="icon-blue" />
          </div>
          <h2 className="text-title" style={{ marginBottom: '12px' }}>AI Stage Missions</h2>
          <p className="text-muted" style={{ marginBottom: '24px', flex: 1 }}>
            Dynamic, infinite challenges generated by CivicMentor AI. Select a stage to focus your training.
          </p>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {allStages.map(stage => {
              const isLocked = stage.order > currentStage.order;
              return (
                <button
                  key={stage.id}
                  onClick={() => {
                    if (!isLocked) {
                      setSelectedStageId(stage.id);
                      setActiveMode('ai');
                    }
                  }}
                  disabled={isLocked}
                  className="btn"
                  style={{
                    display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px',
                    background: 'linear-gradient(to right, var(--bg-elevated), rgba(255,255,255,0.02))', 
                    border: '1px solid var(--border-subtle)',
                    borderRadius: '12px', textAlign: 'left',
                    opacity: isLocked ? 0.5 : 1, cursor: isLocked ? 'not-allowed' : 'pointer',
                    boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
                    transition: 'all 0.3s cubic-bezier(0.25, 0.8, 0.25, 1)'
                  }}
                  onMouseOver={(e) => { 
                    if(!isLocked) { 
                      e.currentTarget.style.borderColor = 'var(--blue)'; 
                      e.currentTarget.style.transform = 'translateY(-4px)';
                      e.currentTarget.style.boxShadow = '0 10px 20px rgba(59, 130, 246, 0.15)';
                      e.currentTarget.style.background = 'linear-gradient(to right, rgba(59, 130, 246, 0.1), var(--bg-elevated))';
                    } 
                  }}
                  onMouseOut={(e) => { 
                    if(!isLocked) { 
                      e.currentTarget.style.borderColor = 'var(--border-subtle)'; 
                      e.currentTarget.style.transform = 'none'; 
                      e.currentTarget.style.boxShadow = '0 4px 6px rgba(0,0,0,0.1)';
                      e.currentTarget.style.background = 'linear-gradient(to right, var(--bg-elevated), rgba(255,255,255,0.02))';
                    } 
                  }}
                >
                  <div>
                    <div style={{ fontWeight: '700', color: 'var(--text-primary)', marginBottom: '4px' }}>{stage.title}</div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>{isLocked ? 'Locked' : 'Available'}</div>
                  </div>
                  {!isLocked && <ChevronRight size={16} className="icon-muted" />}
                </button>
              );
            })}
          </div>
        </div>

        {/* Global Quiz Card */}
        <div className="card premium-card-glass" style={{ padding: '32px', display: 'flex', flexDirection: 'column', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', top: '-20px', right: '-20px', width: '150px', height: '150px', background: 'var(--gold-glow)', filter: 'blur(40px)', borderRadius: '50%', zIndex: 0, pointerEvents: 'none' }}></div>
          <div style={{ width: '48px', height: '48px', background: 'var(--gold-subtle)', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: '24px', zIndex: 1, position: 'relative' }}>
            <Globe size={24} className="icon-gold" />
          </div>
          <h2 className="text-title" style={{ marginBottom: '12px', zIndex: 1, position: 'relative' }}>Global Knowledge</h2>
          <p className="text-muted" style={{ marginBottom: '32px', flex: 1, zIndex: 1, position: 'relative' }}>
            Test your overall civic literacy with the standardized 10-question challenge. Compete on the global leaderboard and earn massive XP.
          </p>
          
          <div style={{ background: 'rgba(0,0,0,0.2)', padding: '16px', borderRadius: '12px', marginBottom: '24px', zIndex: 1, position: 'relative', border: '1px solid rgba(255,255,255,0.05)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '8px', fontSize: '14px' }}>
              <span style={{ color: 'var(--text-muted)' }}>Questions</span>
              <span style={{ color: 'var(--text-primary)', fontWeight: 'bold' }}>10</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '14px' }}>
              <span style={{ color: 'var(--text-muted)' }}>Reward</span>
              <span style={{ color: 'var(--gold)', fontWeight: 'bold' }}>Up to 200 XP</span>
            </div>
          </div>

          <button 
            className="btn btn-gold" 
            onClick={() => setActiveMode('global')}
            style={{ 
              padding: '16px', fontSize: '16px', fontWeight: '800', width: '100%', 
              display: 'flex', justifyContent: 'center', gap: '8px', zIndex: 1, position: 'relative',
              boxShadow: '0 8px 25px rgba(251, 191, 36, 0.3)', textTransform: 'uppercase', letterSpacing: '1px'
            }}
          >
            Start Global Quiz <Globe size={18} />
          </button>
        </div>
      </div>
      </div>
    </div>
  );
}
